spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/es_04_login_test_dev
    username: root
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: pietro.imbrea@gmail.com
    password: gmupqrsdhurfjfse
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8081

application:
  security:
    jwt:
      secret-key: 332225467159544c413f23236d56693a486372456534494b74344c3b66
      expiration: 122222222 # a day
      refresh-token:
        expiration: 604800000 # 7 days

