spring:
  messages:
    basename: messages
  config:
    import: env.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_DATABSE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8081

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 122222222 # a day
      refresh-token:
        expiration: 604800000 # 7 days


