spring:
  datasource:
    url: jdbc:mysql://localhost:3306/es_03
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    generate-ddl: true
  profiles:
    active:

server:
  port: 8080

logging:
  file:
    name: es_03_spring_swagger_database/logs/cocktail.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%-5level] %logger{36} - %msg%n"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){green} %clr([${PID:- }]){magenta} %clr([%-5level]){yellow} %logger{36} - %msg%n"
  level:
    root: info
    org:
      springframework: debug
      hibernate: error
  logback:
    rollingpolicy:
      max-file-size: "10MB"
      max-history: "10"