spring:
  datasource:
    url: jdbc:mysql://localhost:3306/es_03
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    generate-ddl: true

server:
  port: 8081

logging:
  file:
    name: cocktail.log
    path: es_03_spring_swagger_database/logs
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%X{sessionId}] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{sessionId}] %-5level %logger{36} - %msg%n"
  level:
    root: info
    org:
      springframework: debug
      hibernate: error
  logback:
    rollingpolicy:
      max-file-size: "1MB"
      max-history: "10"

