spring:
  datasource:
    url: jdbc:mysql://localhost:3306/es_03
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    generate-ddl: true

server:
  port: 8081

logging:
  file:
    name: es_03_spring_swagger_database/logs/cocktail.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%-5level] %logger{36} - %msg%n"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){green} %clr([${PID:- }]){magenta} %clr([%-5level]){yellow} %logger{36} - %msg%n"
  level:
    root: info
    org:
      springframework: debug
      hibernate: error
  logback:
    rollingpolicy:
      max-file-size: "10MB"
      max-history: "10"

#${FILE_LOG_PATTERN:-%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd'T'HH:mm:ss.SSSXXX}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- ${LOGGED_APPLICATION_NAME:-}[%t] ${LOG_CORRELATION_PATTERN:-}%-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}
#%d{yyyy-MM-dd HH:mm:ss} [%-5level] %logger{36} - %msg%n